export type Url = (typeof urls)[keyof typeof urls];
export const urls = {
  root: '/',
  akashicPay: 'akashic',
  importAccountUrl: 'import',
  welcome: 'welcome',
  dashboard: 'dashboard',
  deposit: 'deposit',
  sendTo: 'send-to',
  sendConfirm: 'send-confirm',
  sendResult: 'send-result',
  nfts: 'nfts',
  nft: 'nft',
  nftTransfer: 'nft-transfer',
  nftTransferResult: 'nft-transfer-result',
  activity: 'activity',
  recoverCode: 'recover-code',
  send: 'send',
  changePassword: 'change-password',
  changePasswordConfirm: 'change-password-confirm',
  error: 'error',
  us2: 'us2',
  manageAccounts: 'manage-account',
  createWalletPassword: 'create-wallet-password',
  createWalletSecretPhrase: 'create-wallet-secret',
  createWalletSecretPhraseConfirm: 'create-wallet-secret-confirm',
  createWalletSuccessful: 'create-wallet-success',
  importWalletPassword: 'import-wallet-password',
  importWalletKeypair: 'import-wallet-keypair',
  importWalletSecretPhrase: 'import-wallet-secret-phrase',
  importWalletSelectMethod: 'import-wallet-select-method',
  importWalletSuccessful: 'import-wallet-success',
  activityDetails: 'activity-details',
  settings: 'settings',
  settingsGeneral: 'settings-general',
  settingsSecurity: 'settings-security',
  settingsNetwork: 'settings-network',
  settingsAboutUs: 'settings-about-us',
  settingsBackup: 'settings-backup',
  settingsVersion: 'settings-version',
} as const;

export const SUPPORT_MAIL = 'support@akashiclink.com';
